// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: robot.proto

#include "robot.pb.h"
#include "robot.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace Robot {
namespace Control {

static const char* RobotControl_method_names[] = {
  "/Robot.Control.RobotControl/WalkTo",
};

std::unique_ptr< RobotControl::Stub> RobotControl::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RobotControl::Stub> stub(new RobotControl::Stub(channel, options));
  return stub;
}

RobotControl::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_WalkTo_(RobotControl_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RobotControl::Stub::WalkTo(::grpc::ClientContext* context, const ::Robot::Control::SpeedReq& request, ::Robot::Control::CoordinatesRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Robot::Control::SpeedReq, ::Robot::Control::CoordinatesRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WalkTo_, context, request, response);
}

void RobotControl::Stub::async::WalkTo(::grpc::ClientContext* context, const ::Robot::Control::SpeedReq* request, ::Robot::Control::CoordinatesRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Robot::Control::SpeedReq, ::Robot::Control::CoordinatesRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WalkTo_, context, request, response, std::move(f));
}

void RobotControl::Stub::async::WalkTo(::grpc::ClientContext* context, const ::Robot::Control::SpeedReq* request, ::Robot::Control::CoordinatesRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WalkTo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Robot::Control::CoordinatesRes>* RobotControl::Stub::PrepareAsyncWalkToRaw(::grpc::ClientContext* context, const ::Robot::Control::SpeedReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Robot::Control::CoordinatesRes, ::Robot::Control::SpeedReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WalkTo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Robot::Control::CoordinatesRes>* RobotControl::Stub::AsyncWalkToRaw(::grpc::ClientContext* context, const ::Robot::Control::SpeedReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWalkToRaw(context, request, cq);
  result->StartCall();
  return result;
}

RobotControl::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotControl_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotControl::Service, ::Robot::Control::SpeedReq, ::Robot::Control::CoordinatesRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Robot::Control::SpeedReq* req,
             ::Robot::Control::CoordinatesRes* resp) {
               return service->WalkTo(ctx, req, resp);
             }, this)));
}

RobotControl::Service::~Service() {
}

::grpc::Status RobotControl::Service::WalkTo(::grpc::ServerContext* context, const ::Robot::Control::SpeedReq* request, ::Robot::Control::CoordinatesRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Robot
}  // namespace Control

